"""orders1.46

Revision ID: 1eb828224bc8
Revises: b8eac36faee5
Create Date: 2025-03-22 18:11:04.195168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eb828224bc8'
down_revision = 'b8eac36faee5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('second_dealer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('articles_dealer_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dealers', ['dealer_id'], ['id'])
        batch_op.create_foreign_key(None, 'dealers', ['second_dealer_id'], ['id'])
        batch_op.drop_column('second_dealer')
        batch_op.drop_column('dealer_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('second_dealer', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articles_dealer_name_fkey', 'dealers', ['dealer_name'], ['name'])
        batch_op.drop_column('second_dealer_id')
        batch_op.drop_column('dealer_id')

    # ### end Alembic commands ###
