"""orders1.12

Revision ID: 373db9f2d258
Revises: d240f24f7055
Create Date: 2025-03-03 02:24:01.701673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '373db9f2d258'
down_revision = 'd240f24f7055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_name', sa.String(), nullable=True))
        batch_op.drop_constraint('articles_dealer_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dealers', ['dealer_name'], ['name'])
        batch_op.drop_column('dealer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articles_dealer_id_fkey', 'dealers', ['dealer_id'], ['id'])
        batch_op.drop_column('dealer_name')

    # ### end Alembic commands ###
