"""multiplicity

Revision ID: 3989aa69069b
Revises: 460dd38d9620
Create Date: 2025-02-25 22:30:59.968630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3989aa69069b'
down_revision = '460dd38d9620'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('multiplicity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('multiplicity')

    # ### end Alembic commands ###
