"""deealer123

Revision ID: 460dd38d9620
Revises: 1be1ec33e7f1
Create Date: 2025-02-18 01:06:28.529894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460dd38d9620'
down_revision = '1be1ec33e7f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dealers', schema=None) as batch_op:
        batch_op.alter_column('phone',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
