"""orders1.03

Revision ID: 7e204f93e47a
Revises: 9802eb5d6084
Create Date: 2025-03-02 22:14:18.912909

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e204f93e47a'
down_revision = '9802eb5d6084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('articles_dealer_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dealers', ['dealer_id'], ['id'])
        batch_op.drop_column('dealer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articles_dealer_fkey', 'dealers', ['dealer'], ['name'])
        batch_op.drop_column('dealer_id')

    # ### end Alembic commands ###
