"""orders1.2

Revision ID: ac057b693e79
Revises: 4cdcc51564fc
Create Date: 2025-02-26 14:05:53.248970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac057b693e79'
down_revision = '4cdcc51564fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_goods', schema=None) as batch_op:
        batch_op.drop_constraint('order_goods_article_id_fkey', type_='foreignkey')
        batch_op.drop_column('article_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_dealer_id_fkey', type_='foreignkey')
        batch_op.drop_column('dealer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_dealer_id_fkey', 'dealers', ['dealer_id'], ['id'])

    with op.batch_alter_table('order_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('order_goods_article_id_fkey', 'articles', ['article_id'], ['id'])

    # ### end Alembic commands ###
