"""orders1.43

Revision ID: b077b08c30a4
Revises: ff42f5969d62
Create Date: 2025-03-22 18:08:47.765232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b077b08c30a4'
down_revision = 'ff42f5969d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('second_dealer_id', sa.Integer(), nullable=True))
        batch_op.alter_column('second_price',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_constraint('articles_dealer_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'dealers', ['second_dealer_id'], ['id'])
        batch_op.create_foreign_key(None, 'dealers', ['dealer_id'], ['id'])
        batch_op.drop_column('dealer_name')
        batch_op.drop_column('second_dealer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_dealer', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dealer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('articles_dealer_name_fkey', 'dealers', ['dealer_name'], ['name'])
        batch_op.alter_column('second_price',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('second_dealer_id')
        batch_op.drop_column('dealer_id')

    # ### end Alembic commands ###
