"""orders1.05

Revision ID: b3954d1768bd
Revises: 7e204f93e47a
Create Date: 2025-03-02 22:38:52.111141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3954d1768bd'
down_revision = '7e204f93e47a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('orders_dealer_id_fkey', type_='foreignkey')
        batch_op.drop_column('dealer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dealer_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('orders_dealer_id_fkey', 'dealers', ['dealer_id'], ['id'])

    # ### end Alembic commands ###
