"""orders1.4

Revision ID: c4b35664395c
Revises: 1df1180ec9d1
Create Date: 2025-02-26 14:11:42.159985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b35664395c'
down_revision = '1df1180ec9d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.String(), nullable=True))
        batch_op.drop_constraint('order_goods_article_name_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'])
        batch_op.drop_column('article_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('order_goods_article_name_fkey', 'articles', ['article_name'], ['name'])
        batch_op.drop_column('article_id')

    # ### end Alembic commands ###
