"""orders1.23

Revision ID: ff42f5969d62
Revises: 98cb89b42967
Create Date: 2025-03-22 15:38:03.591924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff42f5969d62'
down_revision = '98cb89b42967'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_goods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_multiplicity', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_goods', schema=None) as batch_op:
        batch_op.drop_column('article_multiplicity')

    # ### end Alembic commands ###
